travis: tested using Nette Coding Standard

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,28 +18,43 @@ matrix:
     include:
         - php: 7.0
           env: COVERAGE=on
+        - php: 7.1
+          env: CODING_STANDARD=on
 
 script:
-    - src/tester -p $TESTER_PHP_BIN --info
-    - src/tester -p $TESTER_PHP_BIN tests -s $COVERAGE_ARGS
-    - src/tester -p $TESTER_PHP_BIN -o none tests/fail.phptx; if [ $? -eq 0 ]; then echo "tests/fail.phptx SHOULD FAIL"; exit 1; else echo "fail checked"; fi;
-    - php code-checker/src/code-checker.php --no-progress --short-arrays
+    - >
+      if [ "$TESTER_PHP_BIN" ]; then
+      src/tester -p $TESTER_PHP_BIN --info
+      && src/tester -p $TESTER_PHP_BIN tests -s $COVERAGE_ARGS
+      && src/tester -p $TESTER_PHP_BIN -o none tests/fail.phptx; if [ $? -eq 0 ]; then echo "tests/fail.phptx SHOULD FAIL"; exit 1; else echo "fail checked"; fi;
+      fi
+    - >
+      if [ "$CODING_STANDARD" ]; then
+      php temp/code-checker/src/code-checker.php --short-arrays
+      && php temp/coding-standard/ecs check src tests --config tests/coding-standard.neon;
+      fi
 
 after_failure:
     # Print *.actual content
     - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
 
 before_script:
-    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction
-    - if [ "$COVERAGE" == "on" ]; then TESTER_PHP_BIN=phpdbg; COVERAGE_ARGS="--coverage ./coverage.xml --coverage-src ./src"; fi
+    # Install Code Checkers
+    - >
+      if [ "$CODING_STANDARD" ]; then
+      travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-interaction;
+      travis_retry composer create-project nette/coding-standard temp/coding-standard --no-interaction;
+      fi
+
+    - if [ "$COVERAGE" ]; then TESTER_PHP_BIN=phpdbg; COVERAGE_ARGS="--coverage ./coverage.xml --coverage-src ./src"; fi
 
 after_script:
     # Report Code Coverage
     - >
-      if [ "$COVERAGE" == "on" ]; then
+      if [ "$COVERAGE" ]; then
       wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
-      && php coveralls.phar --verbose --config tests/.coveralls.yml
-      || true; fi
+      && php coveralls.phar --verbose --config tests/.coveralls.yml;
+      fi
 
 sudo: false
 
